# Stage 1: Build the .NET Core application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy the project file and restore dependencies
COPY CoffeeShopApi/CoffeeShopApi.csproj ./CoffeeShopApi/
RUN dotnet restore "CoffeeShopApi/CoffeeShopApi.csproj"

# Copy the entire source code and build the application
COPY CoffeeShopApi ./CoffeeShopApi/
WORKDIR /src/CoffeeShopApi
RUN dotnet publish -c Release -o /app

# Stage 2: Use the ASP.NET Core runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .
COPY docker/backend-entrypoint.sh /app/backend-entrypoint.sh
RUN chmod 755 /app/backend-entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/app/backend-entrypoint.sh"]
